create sequence if not exists monitoring.changes_id_seq;
create table if not exists monitoring.changes
(
    id                                   integer not null default nextval('monitoring.changes_id_seq'),
--main object
    created_by                           varchar,
    created_at                           timestamp,
    updated_by                           varchar,
    updated_at                           timestamp,
    closed_by                            varchar,
    closed_at                            timestamp,
    affected_item                        varchar,
    backout_plan                         varchar,
    is_manager_notification              boolean,
    risk_level                           varchar,
    criticality                          varchar,
    change_owner                         varchar,
    build_test_plan                      varchar,
    build_test_result                    varchar,
    affected_cis                         varchar,
    affected_its                         varchar,
    initial_impact                       varchar,
    risk_finance                         varchar,
    was_loading_testing                  varchar,
    func_testing                         varchar,
    sys_impact                           varchar,
    custom_reach                         varchar,
    reserve_system                       varchar,
    rollback_duration                    varchar,
    pr_window_time                       varchar,
    freeze_time                          varchar,
    change_failure                       varchar,
    sensitive_infr_impact                varchar,
    implementation_start_at              timestamp,
    implementation_end_at                timestamp,
    resolution_code                      varchar,
    is_no_downtime                       boolean,
    is_st_chg_candidat                   boolean,
    is_have_report                       boolean,
    template_id                          varchar,
    template_name                        varchar,
    fault_category                       varchar,
    reason_no_cab                        varchar,
-- header
    change_id                            varchar not null,
    current_phase                        varchar,
    status                               varchar,
    category                             varchar,
    subcategory                          varchar,
    brief_description                    varchar,
    requested_by                         varchar,
    requested_for                        varchar,
    assign_dept                          varchar,
    planned_start_at                     varchar,
    planned_end_at                       varchar,
    foreign_id                           varchar,
--  description
    description                          varchar,
    justification                        varchar,
    acceptance_comments                  varchar,
    plan                                 varchar,
    vtb_risk_description                 varchar,
-- middle
    sched_outage_start_at                timestamp,
    sched_outage_end_at                  timestamp,
    assets                               varchar,
    affected_services                    varchar,
    down_start_at                        timestamp,
    down_end_at                          timestamp,
--close
    closing_comments                     varchar
);

alter sequence monitoring.changes_id_seq
owned by monitoring.changes.id;