INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (1, 'Инцидент А_1', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 1');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (2, 'Инцидент А_2', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 2');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (3, 'Инцидент А_3', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 3');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (4, 'Инцидент А_4', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 4');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (5, 'Инцидент А_5', '2020-11-16 16:00:00', 'Проблема', 'Иванов Василий 5');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (6, 'Инцидент А_6', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 6');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (7, 'Инцидент А_7', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 7');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (8, 'Инцидент А_8', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 8');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (9, 'Инцидент А_9', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 9');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (10, 'Инцидент А_10', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 10');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (11, 'Инцидент А_11', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 11');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (12, 'Инцидент А_12', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 12');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (13, 'Инцидент А_13', '2020-11-16 19:00:00', 'Проблема', 'Иванов Василий 13');
INSERT INTO monitoring.incidents (id, incident_id, created_at, description, specialist_id) VALUES (14, 'Проблема А_14', '2020-11-17 19:00:00', 'Самая свежая проблема', 'Иванов Василий 14');

insert into monitoring.systems (name, accidentid) values ('Переводы', 1);
insert into monitoring.systems (name, accidentid) values ('Переводы', 2);
insert into monitoring.systems (name, accidentid) values ('Переводы', 3);
insert into monitoring.systems (name, accidentid) values ('Переводы', 4);
insert into monitoring.systems (name, accidentid) values ('Переводы', 5);
insert into monitoring.systems (name, accidentid) values ('Переводы', 6);
insert into monitoring.systems (name, accidentid) values ('Переводы', 7);
insert into monitoring.systems (name, accidentid) values ('Переводы', 8);
insert into monitoring.systems (name, accidentid) values ('Переводы', 9);
insert into monitoring.systems (name, accidentid) values ('Переводы', 10);
insert into monitoring.systems (name, accidentid) values ('Переводы', 11);
insert into monitoring.systems (name, accidentid) values ('Переводы', 12);
insert into monitoring.systems (name, accidentid) values ('Переводы', 13);

insert into monitoring.systems (name, accidentid) values ('Платежи', 1);
insert into monitoring.systems (name, accidentid) values ('Платежи', 2);
insert into monitoring.systems (name, accidentid) values ('Платежи', 3);
insert into monitoring.systems (name, accidentid) values ('Платежи', 4);
insert into monitoring.systems (name, accidentid) values ('Платежи', 5);
insert into monitoring.systems (name, accidentid) values ('Платежи', 6);
insert into monitoring.systems (name, accidentid) values ('Платежи', 7);
insert into monitoring.systems (name, accidentid) values ('Платежи', 8);
insert into monitoring.systems (name, accidentid) values ('Платежи', 9);
insert into monitoring.systems (name, accidentid) values ('Платежи', 10);
insert into monitoring.systems (name, accidentid) values ('Платежи', 11);
insert into monitoring.systems (name, accidentid) values ('Платежи', 12);
insert into monitoring.systems (name, accidentid) values ('Платежи', 13);
